# Generated by Django 5.2.4 on 2025-08-01 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='pname',
        ),
    ]
